stages:
  - test
  - publish

test:
  stage: test
  image: ruby:2.7
  script:
    - bundle install
    - bundle exec rubocop
    - bundle exec rspec

publish:
  stage: publish
  image: ruby:2.7
  only:
    - main
  script: |
    mkdir -p ${HOME}/.gem
    touch ${HOME}/.gem/credentials
    chmod 0600 ${HOME}/.gem/credentials
    printf -- "---\n:jfrog: Basic $(echo -n $ARTIFACTORY_API_USER:$ARTIFACTORY_API_TOKEN | base64 -w 0)\n" > ${HOME}/.gem/credentials
    gem build hopin-money-utils.gemspec
    GEM="hopin-money-utils-$(ruby -e "puts File.read('lib/hopin/money_utils/version.rb').match(/VERSION = '(.+)'$/)[1]").gem"
    gem push --KEY jfrog --host ${ARTIFACTORY_API_URL_RUBY} ${GEM}

