Lint/EmptyFile:
  Exclude:
  - spec/brightline/intents/**/*.rb
  - spec/brightline/messages/**/*.rb
  - spec/brightline/publishers/**/*.rb

RSpec/EmptyExampleGroup:
  Exclude:
  - spec/brightline/intents/**/*.rb


